import Head from 'next/head'
import NavBar from '../components/NavBar/NavBar'
import css from '../styles/scss/HomePage.module.scss'
import pages from "../constants/pages"
import NavBarSmall from '../components/NavBarSmall/NavBarSmall'
import { useEffect, useState } from 'react'

export default function Home() {
  const [mount, setMount] = useState({
    x: 0,
    y: 0
  })

  const handleMount = (e) => {

    if (e.clientX > 10 && e.clientY > 10) {
      setMount({
        x: e.clientX,
        y: e.clientY
      })
    }
    else {
      setMount({
        x: -100,
        y: -100
      })
    }
  }

  useEffect(() => {
    window.addEventListener('mousemove', handleMount)
  }, [])


  const style = {
    transform: `translate(${mount.x + "px"}, ${mount.y + "px"})`
  }

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header id={css.header}>
        <NavBar />
      </header>
      <NavBarSmall />

      <main id={css.main}>
        {pages.HeroHeader}
        {pages.About}
        {pages.Services}
        {pages.Portfolid}
        {pages.Blog}
        {pages.Constact}
      </main>

      <div className={css.mouseEffect} style={style} id="mouse"></div>
    </>
  )
}
