import Head from 'next/head'
import NavBar from '../components/NavBar/NavBar'
import css from '../styles/scss/HomePage.module.scss'
import pages from "../constants/pages"
import NavBarSmall from '../components/NavBarSmall/NavBarSmall'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header id={css.header}>
        <NavBar />
      </header>
      <NavBarSmall />

      <main id={css.main}>
        {pages.HeroHeader}
        {pages.About}
        {pages.Services}
        {pages.Portfolid}
        {pages.Blog}
        {pages.Constact}
      </main>
    </>
  )
}
