import Head from 'next/head'
import NavBar from '../components/NavBar/NavBar'
import css from '../styles/scss/HomePage.module.scss'
import pages from "../constants/pages"
import { useEffect } from 'react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={css.root}>
        <NavBar />
        <main>
          {pages.HeroHeader}
          {pages.About}
          {pages.Services}
          {pages.Portfolid}
          {pages.Blog}
          {pages.Constact}
        </main>
      </header>
    </>
  )
}
